uploads = []
generated = []

[[outputs]]
id = "44kQSplfzWH6QScAv-wMl"
uri = "file://MAWEJA_Presentation.pdf"
type = "pdf"
title = "MAWEJA — Présentation Officielle (PDF)"

[[outputs]]
id = "pnZiDqLwYZaaXZ0QX4Gj-"
uri = "file://maweja-github.zip"
type = "unspecified"
title = "MAWEJA — Code source complet (à uploader sur GitHub)"

[[outputs]]
id = "YorWQ98XJvCCsGGYHm2py"
uri = "file://MAWEJA_GitHub_Actions.zip"
type = "unspecified"
title = "MAWEJA GitHub Actions — CORRIGÉ (sans erreur lock file)"

[[outputs]]
id = "kcU3Nq_e3Q7YbR1sKVrCe"
uri = "file://MAWEJA_COMPLET_GITHUB.zip"
type = "unspecified"
title = "MAWEJA — Code source complet pour GitHub (796 Ko)"

[[outputs]]
id = "YALVvrGzSsHZKpt0MLEKh"
uri = "file://MAWEJA_COMPLET_GITHUB_v2.zip"
type = "unspecified"
title = "MAWEJA — Code source complet v2 CORRIGÉ (1.6 Mo) — avec logo inclus"

[[outputs]]
id = "PLP4LqM3aK1lpWXyvmQ-1"
uri = "file://MAWEJA_COMPLET_GITHUB_v3.zip"
type = "unspecified"
title = "MAWEJA — Code complet v3 CORRIGÉ (ImageMagick installé automatiquement)"

[[outputs]]
id = "V8Dn6aKSMzs6RhLQIyWQL"
uri = "file://MAWEJA_COMPLET_GITHUB_v4.zip"
type = "unspecified"
title = "MAWEJA_COMPLET_GITHUB_v4.zip — Version corrigée"

[[outputs]]
id = "vH_gFSAQQByBBjUAoztn1"
uri = "file://MAWEJA_COMPLET_GITHUB_v5.zip"
type = "unspecified"
title = "MAWEJA_COMPLET_GITHUB_v5.zip — Tous les bugs APK corrigés"

[[outputs]]
id = "fwXxDKzPFswXlH123pumt"
uri = "file://MAWEJA_COMPLET_GITHUB_v7.zip"
type = "unspecified"
title = "MAWEJA_COMPLET_GITHUB_v7.zip — Code source complet"

[[outputs]]
id = "X2rOyFip1LSEGKhRieJKj"
uri = "file://MAWEJA_v8.zip"
type = "unspecified"
title = "MAWEJA_v8 — Code source complet (GitHub)"

[[outputs]]
id = "6BSXxVpGhtcIuhL5izaEF"
uri = "file://MAWEJA_v9.zip"
type = "unspecified"
title = "MAWEJA_v9.zip — Notifications rétablies (2.4 MB)"

[[outputs]]
id = "NqW2XGA-NICwuGqpffcp3"
uri = "file://MAWEJA_source.zip"
type = "unspecified"
title = "MAWEJA — Code source actualisé (GitHub)"

[[outputs]]
id = "5Mqy7zfbRe8f8MBSiMvht"
uri = "file://maweja-mobile-v2.zip"
type = "unspecified"
title = "MAWEJA Mobile v2 — Source complet (Android/iOS)"

[[outputs]]
id = "pW6Dr8rCyzY6R3Pa16sL4"
uri = "file://MAWEJA_COMPLET_GITHUB_v8.zip"
type = "unspecified"
title = "MAWEJA — GitHub v8 (Source complet)"

[[outputs]]
id = "VlT7m0UURBIgjDuH0D6Wn"
uri = "file://MAWEJA_github_final.zip"
type = "unspecified"
title = "MAWEJA - Code Source complet (GitHub)"

[[outputs]]
id = "s46NA2LX2_RJj5c64I_t0"
uri = "file://MAWEJA_github_v2.zip"
type = "unspecified"
title = "MAWEJA - Code Source GitHub v2 (icons-only nav + dark mode complet)"
