uploads = []
generated = []

[[outputs]]
id = "44kQSplfzWH6QScAv-wMl"
uri = "file://MAWEJA_Presentation.pdf"
type = "pdf"
title = "MAWEJA — Présentation Officielle (PDF)"

[[outputs]]
id = "pnZiDqLwYZaaXZ0QX4Gj-"
uri = "file://maweja-github.zip"
type = "unspecified"
title = "MAWEJA — Code source complet (à uploader sur GitHub)"

[[outputs]]
id = "YorWQ98XJvCCsGGYHm2py"
uri = "file://MAWEJA_GitHub_Actions.zip"
type = "unspecified"
title = "MAWEJA GitHub Actions — Android + iOS (prêt pour GitHub)"
