import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useI18n } from "../../lib/i18n";
import { useAuth } from "../../lib/auth";
import ClientNav from "../../components/ClientNav";
import { ArrowLeft, Globe, ChevronRight, Bell, Shield, HelpCircle, Info } from "lucide-react";
import { useLocation } from "wouter";
export default function ClientSettings() {
    const [, navigate] = useLocation();
    const { lang, setLang, t } = useI18n();
    const { user } = useAuth();
    return (_jsxs("div", { className: "min-h-screen bg-gray-50 pb-24", children: [_jsx(ClientNav, {}), _jsxs("div", { className: "max-w-lg mx-auto px-4 py-4", children: [_jsxs("div", { className: "flex items-center gap-3 mb-6", children: [_jsx("button", { onClick: () => navigate("/"), className: "w-10 h-10 bg-white rounded-xl flex items-center justify-center border border-gray-200", "data-testid": "button-back", children: _jsx(ArrowLeft, { size: 18 }) }), _jsx("h2", { className: "text-xl font-black text-gray-900", "data-testid": "text-settings-title", children: t.settings.title })] }), _jsxs("div", { className: "bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden mb-4", children: [_jsx("div", { className: "px-5 py-4 border-b border-gray-50", children: _jsxs("h3", { className: "font-bold text-sm text-gray-900 flex items-center gap-2", children: [_jsx(Globe, { size: 16, className: "text-red-500" }), t.settings.language] }) }), _jsxs("div", { className: "p-4 space-y-2", children: [_jsxs("button", { onClick: () => setLang("fr"), "data-testid": "button-lang-fr", className: `w-full flex items-center gap-3 px-4 py-3 rounded-xl transition-all ${lang === "fr" ? "bg-red-50 border-2 border-red-500" : "bg-gray-50 border-2 border-transparent hover:border-gray-200"}`, children: [_jsx("span", { className: "text-xl", children: "\uD83C\uDDEB\uD83C\uDDF7" }), _jsx("span", { className: "font-semibold text-sm text-gray-900", children: t.common.french }), lang === "fr" && _jsx("span", { className: "ml-auto text-red-600 font-bold text-xs", children: "\u2713" })] }), _jsxs("button", { onClick: () => setLang("en"), "data-testid": "button-lang-en", className: `w-full flex items-center gap-3 px-4 py-3 rounded-xl transition-all ${lang === "en" ? "bg-red-50 border-2 border-red-500" : "bg-gray-50 border-2 border-transparent hover:border-gray-200"}`, children: [_jsx("span", { className: "text-xl", children: "\uD83C\uDDEC\uD83C\uDDE7" }), _jsx("span", { className: "font-semibold text-sm text-gray-900", children: t.common.english }), lang === "en" && _jsx("span", { className: "ml-auto text-red-600 font-bold text-xs", children: "\u2713" })] })] })] }), _jsx("div", { className: "bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden", children: _jsx("div", { className: "divide-y divide-gray-50", children: [
                                { icon: Bell, label: t.settings.notifications, testId: "button-notif" },
                                { icon: Shield, label: t.settings.privacyPolicy, testId: "button-privacy" },
                                { icon: HelpCircle, label: t.settings.contactSupport, testId: "button-support" },
                                { icon: Info, label: t.settings.about, testId: "button-about" },
                            ].map((item) => (_jsxs("button", { "data-testid": item.testId, className: "w-full flex items-center gap-3 px-5 py-4 hover:bg-gray-50 transition-colors", children: [_jsx(item.icon, { size: 18, className: "text-gray-400" }), _jsx("span", { className: "text-sm font-medium text-gray-700 flex-1 text-left", children: item.label }), _jsx(ChevronRight, { size: 16, className: "text-gray-300" })] }, item.label))) }) }), _jsx("p", { className: "text-center text-[10px] text-gray-400 mt-6 font-medium", children: "MAWEJA v1.0 - Made By Khevin Andrew Kita - Ed Corporation" })] })] }));
}
//# sourceMappingURL=ClientSettings.js.map