import { type User, type InsertUser, type Restaurant, type InsertRestaurant, type MenuItem, type InsertMenuItem, type Order, type InsertOrder, type Notification, type InsertNotification, type ChatMessage, type InsertChatMessage, type WalletTransaction, type InsertWalletTransaction, type Finance, type InsertFinance, type SavedAddress, type InsertSavedAddress } from "@shared/schema";
export interface IStorage {
    getUser(id: number): Promise<User | undefined>;
    getUserByEmail(email: string): Promise<User | undefined>;
    createUser(user: InsertUser): Promise<User>;
    updateUser(id: number, data: Partial<User>): Promise<User | undefined>;
    deleteUser(id: number): Promise<void>;
    getDrivers(): Promise<User[]>;
    getOnlineDrivers(): Promise<User[]>;
    getClients(): Promise<User[]>;
    getAllUsers(): Promise<User[]>;
    getRestaurants(): Promise<Restaurant[]>;
    getRestaurant(id: number): Promise<Restaurant | undefined>;
    createRestaurant(r: InsertRestaurant): Promise<Restaurant>;
    updateRestaurant(id: number, data: Partial<Restaurant>): Promise<Restaurant | undefined>;
    deleteRestaurant(id: number): Promise<void>;
    getMenuItems(restaurantId: number): Promise<MenuItem[]>;
    createMenuItem(item: InsertMenuItem): Promise<MenuItem>;
    updateMenuItem(id: number, data: Partial<MenuItem>): Promise<MenuItem | undefined>;
    deleteMenuItem(id: number): Promise<void>;
    getOrders(filters?: {
        clientId?: number;
        driverId?: number;
        status?: string;
        dateFrom?: Date;
        dateTo?: Date;
    }): Promise<Order[]>;
    getOrder(id: number): Promise<Order | undefined>;
    getOrderByNumber(orderNumber: string): Promise<Order | undefined>;
    createOrder(order: InsertOrder): Promise<Order>;
    updateOrder(id: number, data: Partial<Order>): Promise<Order | undefined>;
    getNotifications(userId: number): Promise<Notification[]>;
    createNotification(n: InsertNotification): Promise<Notification>;
    markNotificationRead(id: number): Promise<void>;
    markAllNotificationsRead(userId: number): Promise<void>;
    getChatMessages(userId1: number, userId2: number): Promise<ChatMessage[]>;
    getChatContacts(userId: number): Promise<any[]>;
    createChatMessage(msg: InsertChatMessage): Promise<ChatMessage>;
    updateChatMessage(id: number, data: Partial<ChatMessage>): Promise<void>;
    getWalletTransactions(userId: number): Promise<WalletTransaction[]>;
    createWalletTransaction(t: InsertWalletTransaction): Promise<WalletTransaction>;
    getFinances(filters?: {
        type?: string;
        dateFrom?: Date;
        dateTo?: Date;
    }): Promise<Finance[]>;
    createFinance(f: InsertFinance): Promise<Finance>;
    getFinanceSummary(dateFrom?: Date, dateTo?: Date): Promise<any>;
    getSavedAddresses(userId: number): Promise<SavedAddress[]>;
    createSavedAddress(addr: InsertSavedAddress): Promise<SavedAddress>;
    updateSavedAddress(id: number, data: Partial<SavedAddress>): Promise<SavedAddress | undefined>;
    deleteSavedAddress(id: number): Promise<void>;
    setDefaultAddress(userId: number, addressId: number): Promise<void>;
    getDashboardStats(): Promise<any>;
}
export declare class DatabaseStorage implements IStorage {
    getUser(id: number): Promise<{
        id: number;
        email: string;
        password: string;
        name: string;
        phone: string;
        role: string;
        avatar: string | null;
        walletBalance: number;
        loyaltyPoints: number;
        isOnline: boolean;
        isBlocked: boolean;
        lat: number | null;
        lng: number | null;
        address: string | null;
        vehicleType: string | null;
        vehiclePlate: string | null;
        driverLicense: string | null;
        commissionRate: number | null;
        sex: string | null;
        dateOfBirth: string | null;
        fullAddress: string | null;
        idPhotoUrl: string | null;
        profilePhotoUrl: string | null;
        verificationStatus: string | null;
        rejectedFields: unknown;
        createdAt: Date | null;
    }>;
    getUserByEmail(email: string): Promise<{
        id: number;
        email: string;
        password: string;
        name: string;
        phone: string;
        role: string;
        avatar: string | null;
        walletBalance: number;
        loyaltyPoints: number;
        isOnline: boolean;
        isBlocked: boolean;
        lat: number | null;
        lng: number | null;
        address: string | null;
        vehicleType: string | null;
        vehiclePlate: string | null;
        driverLicense: string | null;
        commissionRate: number | null;
        sex: string | null;
        dateOfBirth: string | null;
        fullAddress: string | null;
        idPhotoUrl: string | null;
        profilePhotoUrl: string | null;
        verificationStatus: string | null;
        rejectedFields: unknown;
        createdAt: Date | null;
    }>;
    createUser(user: InsertUser): Promise<{
        id: number;
        email: string;
        password: string;
        name: string;
        phone: string;
        role: string;
        avatar: string | null;
        walletBalance: number;
        loyaltyPoints: number;
        isOnline: boolean;
        isBlocked: boolean;
        lat: number | null;
        lng: number | null;
        address: string | null;
        vehicleType: string | null;
        vehiclePlate: string | null;
        driverLicense: string | null;
        commissionRate: number | null;
        sex: string | null;
        dateOfBirth: string | null;
        fullAddress: string | null;
        idPhotoUrl: string | null;
        profilePhotoUrl: string | null;
        verificationStatus: string | null;
        rejectedFields: unknown;
        createdAt: Date | null;
    }>;
    updateUser(id: number, data: Partial<User>): Promise<{
        id: number;
        email: string;
        password: string;
        name: string;
        phone: string;
        role: string;
        avatar: string | null;
        walletBalance: number;
        loyaltyPoints: number;
        isOnline: boolean;
        isBlocked: boolean;
        lat: number | null;
        lng: number | null;
        address: string | null;
        vehicleType: string | null;
        vehiclePlate: string | null;
        driverLicense: string | null;
        commissionRate: number | null;
        sex: string | null;
        dateOfBirth: string | null;
        fullAddress: string | null;
        idPhotoUrl: string | null;
        profilePhotoUrl: string | null;
        verificationStatus: string | null;
        rejectedFields: unknown;
        createdAt: Date | null;
    }>;
    deleteUser(id: number): Promise<void>;
    getDrivers(): Promise<{
        id: number;
        email: string;
        password: string;
        name: string;
        phone: string;
        role: string;
        avatar: string | null;
        walletBalance: number;
        loyaltyPoints: number;
        isOnline: boolean;
        isBlocked: boolean;
        lat: number | null;
        lng: number | null;
        address: string | null;
        vehicleType: string | null;
        vehiclePlate: string | null;
        driverLicense: string | null;
        commissionRate: number | null;
        sex: string | null;
        dateOfBirth: string | null;
        fullAddress: string | null;
        idPhotoUrl: string | null;
        profilePhotoUrl: string | null;
        verificationStatus: string | null;
        rejectedFields: unknown;
        createdAt: Date | null;
    }[]>;
    getOnlineDrivers(): Promise<{
        id: number;
        email: string;
        password: string;
        name: string;
        phone: string;
        role: string;
        avatar: string | null;
        walletBalance: number;
        loyaltyPoints: number;
        isOnline: boolean;
        isBlocked: boolean;
        lat: number | null;
        lng: number | null;
        address: string | null;
        vehicleType: string | null;
        vehiclePlate: string | null;
        driverLicense: string | null;
        commissionRate: number | null;
        sex: string | null;
        dateOfBirth: string | null;
        fullAddress: string | null;
        idPhotoUrl: string | null;
        profilePhotoUrl: string | null;
        verificationStatus: string | null;
        rejectedFields: unknown;
        createdAt: Date | null;
    }[]>;
    getClients(): Promise<{
        id: number;
        email: string;
        password: string;
        name: string;
        phone: string;
        role: string;
        avatar: string | null;
        walletBalance: number;
        loyaltyPoints: number;
        isOnline: boolean;
        isBlocked: boolean;
        lat: number | null;
        lng: number | null;
        address: string | null;
        vehicleType: string | null;
        vehiclePlate: string | null;
        driverLicense: string | null;
        commissionRate: number | null;
        sex: string | null;
        dateOfBirth: string | null;
        fullAddress: string | null;
        idPhotoUrl: string | null;
        profilePhotoUrl: string | null;
        verificationStatus: string | null;
        rejectedFields: unknown;
        createdAt: Date | null;
    }[]>;
    getAllUsers(): Promise<{
        id: number;
        email: string;
        password: string;
        name: string;
        phone: string;
        role: string;
        avatar: string | null;
        walletBalance: number;
        loyaltyPoints: number;
        isOnline: boolean;
        isBlocked: boolean;
        lat: number | null;
        lng: number | null;
        address: string | null;
        vehicleType: string | null;
        vehiclePlate: string | null;
        driverLicense: string | null;
        commissionRate: number | null;
        sex: string | null;
        dateOfBirth: string | null;
        fullAddress: string | null;
        idPhotoUrl: string | null;
        profilePhotoUrl: string | null;
        verificationStatus: string | null;
        rejectedFields: unknown;
        createdAt: Date | null;
    }[]>;
    getRestaurants(): Promise<{
        id: number;
        name: string;
        description: string;
        cuisine: string;
        image: string;
        logoUrl: string | null;
        coverVideoUrl: string | null;
        address: string;
        rating: number;
        deliveryTime: string;
        deliveryFee: number;
        minOrder: number;
        isActive: boolean;
        lat: number | null;
        lng: number | null;
        phone: string | null;
        openingHours: string | null;
        email: string | null;
        managerName: string | null;
        brandName: string | null;
        hqAddress: string | null;
        prepTime: string | null;
    }[]>;
    getRestaurant(id: number): Promise<{
        id: number;
        name: string;
        description: string;
        cuisine: string;
        image: string;
        logoUrl: string | null;
        coverVideoUrl: string | null;
        address: string;
        rating: number;
        deliveryTime: string;
        deliveryFee: number;
        minOrder: number;
        isActive: boolean;
        lat: number | null;
        lng: number | null;
        phone: string | null;
        openingHours: string | null;
        email: string | null;
        managerName: string | null;
        brandName: string | null;
        hqAddress: string | null;
        prepTime: string | null;
    }>;
    createRestaurant(r: InsertRestaurant): Promise<{
        id: number;
        email: string | null;
        name: string;
        phone: string | null;
        lat: number | null;
        lng: number | null;
        address: string;
        description: string;
        cuisine: string;
        image: string;
        logoUrl: string | null;
        coverVideoUrl: string | null;
        rating: number;
        deliveryTime: string;
        deliveryFee: number;
        minOrder: number;
        isActive: boolean;
        openingHours: string | null;
        managerName: string | null;
        brandName: string | null;
        hqAddress: string | null;
        prepTime: string | null;
    }>;
    updateRestaurant(id: number, data: Partial<Restaurant>): Promise<{
        id: number;
        name: string;
        description: string;
        cuisine: string;
        image: string;
        logoUrl: string | null;
        coverVideoUrl: string | null;
        address: string;
        rating: number;
        deliveryTime: string;
        deliveryFee: number;
        minOrder: number;
        isActive: boolean;
        lat: number | null;
        lng: number | null;
        phone: string | null;
        openingHours: string | null;
        email: string | null;
        managerName: string | null;
        brandName: string | null;
        hqAddress: string | null;
        prepTime: string | null;
    }>;
    deleteRestaurant(id: number): Promise<void>;
    getMenuItems(restaurantId: number): Promise<{
        id: number;
        restaurantId: number;
        name: string;
        description: string;
        price: number;
        image: string;
        category: string;
        isAvailable: boolean;
        popular: boolean;
    }[]>;
    createMenuItem(item: InsertMenuItem): Promise<{
        id: number;
        name: string;
        description: string;
        image: string;
        restaurantId: number;
        price: number;
        category: string;
        isAvailable: boolean;
        popular: boolean;
    }>;
    updateMenuItem(id: number, data: Partial<MenuItem>): Promise<{
        id: number;
        restaurantId: number;
        name: string;
        description: string;
        price: number;
        image: string;
        category: string;
        isAvailable: boolean;
        popular: boolean;
    }>;
    deleteMenuItem(id: number): Promise<void>;
    getOrders(filters?: {
        clientId?: number;
        driverId?: number;
        status?: string;
        dateFrom?: Date;
        dateTo?: Date;
    }): Promise<{
        id: number;
        orderNumber: string;
        clientId: number;
        restaurantId: number;
        driverId: number | null;
        status: string;
        items: unknown;
        subtotal: number;
        deliveryFee: number;
        commission: number;
        total: number;
        paymentMethod: string;
        paymentStatus: string;
        deliveryAddress: string;
        deliveryLat: number | null;
        deliveryLng: number | null;
        notes: string | null;
        estimatedDelivery: string | null;
        rating: number | null;
        feedback: string | null;
        cancelReason: string | null;
        taxAmount: number;
        promoCode: string | null;
        promoDiscount: number;
        deviceType: string | null;
        auditLog: unknown;
        createdAt: Date | null;
        updatedAt: Date | null;
    }[]>;
    getOrder(id: number): Promise<{
        id: number;
        orderNumber: string;
        clientId: number;
        restaurantId: number;
        driverId: number | null;
        status: string;
        items: unknown;
        subtotal: number;
        deliveryFee: number;
        commission: number;
        total: number;
        paymentMethod: string;
        paymentStatus: string;
        deliveryAddress: string;
        deliveryLat: number | null;
        deliveryLng: number | null;
        notes: string | null;
        estimatedDelivery: string | null;
        rating: number | null;
        feedback: string | null;
        cancelReason: string | null;
        taxAmount: number;
        promoCode: string | null;
        promoDiscount: number;
        deviceType: string | null;
        auditLog: unknown;
        createdAt: Date | null;
        updatedAt: Date | null;
    }>;
    getOrderByNumber(orderNumber: string): Promise<{
        id: number;
        orderNumber: string;
        clientId: number;
        restaurantId: number;
        driverId: number | null;
        status: string;
        items: unknown;
        subtotal: number;
        deliveryFee: number;
        commission: number;
        total: number;
        paymentMethod: string;
        paymentStatus: string;
        deliveryAddress: string;
        deliveryLat: number | null;
        deliveryLng: number | null;
        notes: string | null;
        estimatedDelivery: string | null;
        rating: number | null;
        feedback: string | null;
        cancelReason: string | null;
        taxAmount: number;
        promoCode: string | null;
        promoDiscount: number;
        deviceType: string | null;
        auditLog: unknown;
        createdAt: Date | null;
        updatedAt: Date | null;
    }>;
    createOrder(order: InsertOrder): Promise<{
        id: number;
        createdAt: Date | null;
        rating: number | null;
        deliveryFee: number;
        restaurantId: number;
        orderNumber: string;
        clientId: number;
        driverId: number | null;
        status: string;
        items: unknown;
        subtotal: number;
        commission: number;
        total: number;
        paymentMethod: string;
        paymentStatus: string;
        deliveryAddress: string;
        deliveryLat: number | null;
        deliveryLng: number | null;
        notes: string | null;
        estimatedDelivery: string | null;
        feedback: string | null;
        cancelReason: string | null;
        taxAmount: number;
        promoCode: string | null;
        promoDiscount: number;
        deviceType: string | null;
        auditLog: unknown;
        updatedAt: Date | null;
    }>;
    updateOrder(id: number, data: Partial<Order>): Promise<{
        id: number;
        orderNumber: string;
        clientId: number;
        restaurantId: number;
        driverId: number | null;
        status: string;
        items: unknown;
        subtotal: number;
        deliveryFee: number;
        commission: number;
        total: number;
        paymentMethod: string;
        paymentStatus: string;
        deliveryAddress: string;
        deliveryLat: number | null;
        deliveryLng: number | null;
        notes: string | null;
        estimatedDelivery: string | null;
        rating: number | null;
        feedback: string | null;
        cancelReason: string | null;
        taxAmount: number;
        promoCode: string | null;
        promoDiscount: number;
        deviceType: string | null;
        auditLog: unknown;
        createdAt: Date | null;
        updatedAt: Date | null;
    }>;
    getNotifications(userId: number): Promise<{
        id: number;
        userId: number;
        title: string;
        message: string;
        type: string;
        isRead: boolean;
        data: unknown;
        createdAt: Date | null;
    }[]>;
    createNotification(n: InsertNotification): Promise<{
        id: number;
        data: unknown;
        createdAt: Date | null;
        userId: number;
        title: string;
        message: string;
        type: string;
        isRead: boolean;
    }>;
    markNotificationRead(id: number): Promise<void>;
    markAllNotificationsRead(userId: number): Promise<void>;
    getChatMessages(userId1: number, userId2: number): Promise<{
        id: number;
        senderId: number;
        receiverId: number;
        orderId: number | null;
        message: string;
        isRead: boolean;
        createdAt: Date | null;
    }[]>;
    getChatContacts(userId: number): Promise<{
        id: number;
        name: string;
        phone: string;
        role: string;
    }[]>;
    createChatMessage(msg: InsertChatMessage): Promise<{
        id: number;
        createdAt: Date | null;
        message: string;
        isRead: boolean;
        senderId: number;
        receiverId: number;
        orderId: number | null;
    }>;
    updateChatMessage(id: number, data: Partial<ChatMessage>): Promise<void>;
    getWalletTransactions(userId: number): Promise<{
        id: number;
        userId: number;
        amount: number;
        type: string;
        description: string;
        reference: string | null;
        orderId: number | null;
        createdAt: Date | null;
    }[]>;
    createWalletTransaction(t: InsertWalletTransaction): Promise<{
        id: number;
        createdAt: Date | null;
        description: string;
        userId: number;
        type: string;
        orderId: number | null;
        amount: number;
        reference: string | null;
    }>;
    getFinances(filters?: {
        type?: string;
        dateFrom?: Date;
        dateTo?: Date;
    }): Promise<{
        id: number;
        type: string;
        category: string;
        amount: number;
        description: string;
        orderId: number | null;
        userId: number | null;
        reference: string | null;
        createdAt: Date | null;
    }[]>;
    createFinance(f: InsertFinance): Promise<{
        id: number;
        createdAt: Date | null;
        description: string;
        category: string;
        userId: number | null;
        type: string;
        orderId: number | null;
        amount: number;
        reference: string | null;
    }>;
    getFinanceSummary(dateFrom?: Date, dateTo?: Date): Promise<{
        summary: {
            totalRevenue: number;
            totalExpense: number;
            totalCommission: number;
            totalDeliveryFees: number;
            count: number;
        };
        byCategory: {
            category: string;
            type: string;
            total: number;
            count: number;
        }[];
        daily: {
            date: string;
            revenue: number;
            expense: number;
        }[];
    }>;
    getDashboardStats(): Promise<{
        orders: {
            total: number;
            pending: number;
            active: number;
            delivered: number;
            cancelled: number;
            revenue: number;
            todayOrders: number;
            todayRevenue: number;
        };
        drivers: {
            total: number;
            online: number;
            blocked: number;
        };
        clients: {
            total: number;
        };
        restaurants: {
            total: number;
            active: number;
        };
    }>;
    getSavedAddresses(userId: number): Promise<{
        id: number;
        userId: number;
        label: string;
        address: string;
        lat: number | null;
        lng: number | null;
        isDefault: boolean;
        createdAt: Date | null;
    }[]>;
    createSavedAddress(addr: InsertSavedAddress): Promise<{
        id: number;
        lat: number | null;
        lng: number | null;
        address: string;
        createdAt: Date | null;
        userId: number;
        label: string;
        isDefault: boolean;
    }>;
    updateSavedAddress(id: number, data: Partial<SavedAddress>): Promise<{
        id: number;
        userId: number;
        label: string;
        address: string;
        lat: number | null;
        lng: number | null;
        isDefault: boolean;
        createdAt: Date | null;
    }>;
    deleteSavedAddress(id: number): Promise<void>;
    setDefaultAddress(userId: number, addressId: number): Promise<void>;
}
export declare const storage: DatabaseStorage;
//# sourceMappingURL=storage.d.ts.map